### ISSUE TITLE
cannot enter capital letters in Input dialog

### ISSUE THREAD

**Issue by cking** [mitsuhiko/dialoguer#105]
everytime i try to enter a capital letter (or rather press shift) i get a "Not a terminal" error.
Application output is the following:

```
✔ Instance Server? · https://b.z0ne.social
✔ Instance API? · Honk
? Username? › Feb 23 14:32:52.984 ERROR ThreadId(01) tracing_unwrap: called `Result::unwrap_or_log()` on an `Err` value: Not a terminal
thread 'main' panicked at 'explicit panic', src\main.rs:36:16
stack backtrace:
   0: std::panicking::begin_panic<str*>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:521
   1: tracing_unwrap::failed_with
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tracing-unwrap-0.9.2\src\lib.rs:287
   2: tracing_unwrap::{{impl}}::unwrap_or_log<tuple<>,anyhow::Error>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\tracing-unwrap-0.9.2\src\lib.rs:133
   3: smexy::main
             at .\src\main.rs:36
   4: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\smexy.exe init` (exit code: 101)
```

Im calling dialoguer like this:
```rust
                            username: Input::<String>::with_theme(&ColorfulTheme::default())
                                .with_prompt("Username?")
                                .interact_text()?,
```

I need to run dialoguer with `interact`, even though `interact_text` should work form documentation perspective

**Comment by pksunkara** [comment]
Yup, known issue, fixing soon. https://github.com/mitsuhiko/console/issues/83

**Comment by cking** [comment]
ah sorry, havent seen taht issue, my bad
